In [1]:
import pandas as pd
import numpy as np

In [2]:
train=pd.read_csv('/Users/boris/Desktop/OZP/train.csv',delimiter=',')

In [3]:
train

,user,event,invited,timestamp,interested,not_interested
0,3044012,1918771225,0,2012-10-02 15:53:05.754000+00:00,0,0
1,3044012,1502284248,0,2012-10-02 15:53:05.754000+00:00,0,0
2,3044012,2529072432,0,2012-10-02 15:53:05.754000+00:00,1,0
3,3044012,3072478280,0,2012-10-02 15:53:05.754000+00:00,0,0
4,3044012,1390707377,0,2012-10-02 15:53:05.754000+00:00,0,0
5,3044012,1532377761,0,2012-10-02 15:53:05.754000+00:00,0,0
6,4236494,2352676247,0,2012-10-30 01:48:25.617000+00:00,0,0
7,4236494,152418051,0,2012-10-30 01:48:28.645000+00:00,1,0
8,4236494,4203627753,0,2012-10-30 01:49:14.152000+00:00,1,0
9,4236494,110357109,0,2012-10-30 01:48:25.617000+00:00,0,0
10,4236494,799782433,0,2012-10-30 01:48:25.617000+00:00,1,0
11,4236494,823015621,0,2012-10-30 01:48:25.617000+00:00,0,0
12,4236494,2790605371,0,2012-10-30 01:48:25.617000+00:00,0,0
13,5574997,941853303,0,2012-11-18 21:43:36.519000+00:00,1,0
14,5574997,623506969,0,2012-11-18 21:43:36.519000+00:00,0,0
15,5574997,1116957623,0,2012-11-18 21:43:36.519000+00:00,0,0
16,5574997,1423412400,0,2012-11-18 21:43:36.519000+00:00,0,0
17,5574997,1916133216,0,2012-11-18 21:43:36.519000+00:00,0,0
18,5574997,4227005710,0,2012-11-18 21:43:36.519000+00:00,0,0
19,7547671,3891122666,0,2012-12-06 13:40:49.700000+00:00,0,0
20,7547671,1500808029,0,2012-12-06 13:40:49.700000+00:00,0,0
21,7547671,2573061069,0,2012-12-06 13:40:49.700000+00:00,0,0
22,7547671,1228445722,0,2012-12-06 13:40:49.700000+00:00,1,0
23,7547671,2433864694,0,2012-12-06 13:40:49.700000+00:00,0,0
24,7547671,3428807031,0,2012-12-06 13:40:49.700000+00:00,0,0
25,10329108,1287318780,0,2012-11-07 03:05:24.446000+00:00,0,0
26,10329108,600752472,0,2012-11-07 03:05:24.446000+00:00,0,0
27,10329108,1940922842,0,2012-11-07 03:05:24.446000+00:00,0,0
28,10329108,788687116,0,2012-11-07 03:05:24.446000+00:00,0,0
29,10329108,40254649,0,2012-11-07 03:05:24.446000+00:00,1,0
...,...,...,...,...,...,...
15368,4285564534,1364943007,0,2012-10-18 10:28:59.399000+00:00,0,0
15369,4285564534,663767875,0,2012-10-18 10:28:59.399000+00:00,1,0
15370,4285564534,675426904,0,2012-10-18 10:28:59.399000+00:00,0,0
15371,4285564534,3874905711,0,2012-10-18 10:28:59.399000+00:00,0,0
15372,4286635694,3580442023,0,2012-12-04 10:37:39.033000+00:00,0,0
15373,4286635694,281688155,0,2012-12-04 10:37:39.033000+00:00,0,0
15374,4286635694,124989980,0,2012-12-04 10:37:39.033000+00:00,0,0
15375,4286635694,904102962,0,2012-12-04 10:37:46.126000+00:00,1,0
15376,4286635694,1449747272,0,2012-12-04 10:37:39.033000+00:00,0,0
15377,4286635694,750220836,0,2012-12-04 10:37:39.033000+00:00,1,0
15378,4286635694,1868620616,0,2012-12-04 10:37:53.687000+00:00,1,0
15379,4286635694,3162029336,0,2012-12-04 10:37:39.033000+00:00,0,0
15380,4288238269,373308576,0,2012-10-22 14:29:15.160000+00:00,1,0
15381,4288238269,2806259041,0,2012-10-22 14:29:15.160000+00:00,0,0
15382,4288238269,1347934681,0,2012-10-22 14:29:15.160000+00:00,0,0
15383,4288238269,3783800124,0,2012-10-22 14:29:39.003000+00:00,1,0
15384,4288238269,85168518,0,2012-10-22 14:29:15.160000+00:00,0,0
15385,4288238269,3867317684,0,2012-10-22 14:29:15.160000+00:00,0,0
15386,4291083982,2753805623,0,2012-10-04 10:07:33.022000+00:00,0,0
15387,4291083982,2072616125,1,2012-10-04 10:07:33.022000+00:00,1,0
15388,4291083982,2988656322,0,2012-10-04 10:07:33.022000+00:00,0,0
15389,4291083982,395593428,0,2012-10-04 10:07:33.022000+00:00,0,0
15390,4291083982,548484748,0,2012-10-04 10:07:33.022000+00:00,0,0
15391,4291083982,558937896,0,2012-10-04 10:07:33.022000+00:00,0,0
15392,4293103086,1431416915,0,2012-12-08 03:59:43.169000+00:00,0,0
15393,4293103086,2750873665,0,2012-12-08 03:59:43.169000+00:00,0,0
15394,4293103086,4084655790,0,2012-12-08 03:59:43.169000+00:00,0,0
15395,4293103086,598708806,0,2012-12-08 03:59:43.169000+00:00,0,0
15396,4293103086,604179853,0,2012-12-08 03:59:43.169000+00:00,0,0
15397,4293103086,2351245308,0,2012-12-08 03:59:43.169000+00:00,1,0

In [4]:
train = train.rename(columns={'user': 'user_id', 'event': 'event_id'})

In [5]:
events=pd.read_csv('/Users/boris/Desktop/OZP/events.csv',delimiter=',')

In [6]:
events.shape

(3137972, 110)

In [7]:
event_attendees=pd.read_csv('/Users/boris/Desktop/OZP/event_attendees.csv',delimiter=',')

In [8]:
event_attendees['yes_count']=event_attendees.yes.str.count(';')+1
event_attendees['no_count']=event_attendees.no.str.count(';')+1
event_attendees['maybe_count']=event_attendees.maybe.str.count(';')+1
event_attendees['invited_count']=event_attendees.invited.str.count(';')+1
event_attendees1=event_attendees.drop(axis=1,labels={'yes','maybe','no','invited'})
event_attendees1.fillna(0, inplace=True)
event_attendees1

,event,yes_count,no_count,maybe_count,invited_count
0,1159822043,7.0,2.0,7.0,70.0
1,686467261,11.0,0.0,8.0,75.0
2,1186208412,0.0,2.0,2.0,2.0
3,2621578336,0.0,0.0,0.0,0.0
4,855842686,6.0,1.0,6.0,10.0
5,2018671985,0.0,0.0,0.0,0.0
6,488116622,45.0,19.0,38.0,166.0
7,1273761447,28.0,12.0,36.0,194.0
8,2688888297,31.0,4.0,34.0,257.0
9,3870329460,0.0,4.0,1.0,143.0
10,3041357942,50.0,9.0,26.0,84.0
11,1343362100,25.0,4.0,18.0,86.0
12,902869993,8.0,2.0,7.0,31.0
13,4287805508,1.0,2.0,0.0,0.0
14,3237640011,33.0,5.0,29.0,177.0
15,1253460052,17.0,8.0,11.0,238.0
16,1146303074,97.0,10.0,109.0,122.0
17,702719295,121.0,22.0,28.0,93.0
18,1065105432,17.0,3.0,17.0,97.0
19,708953850,30.0,2.0,15.0,83.0
20,1569724224,140.0,13.0,71.0,324.0
21,1088978296,32.0,2.0,29.0,44.0
22,3093414446,9.0,4.0,8.0,50.0
23,3863338446,31.0,2.0,19.0,37.0
24,3794291616,36.0,4.0,8.0,52.0
25,4257575686,2.0,15.0,1.0,171.0
26,1474957705,24.0,13.0,23.0,80.0
27,2350744455,10.0,10.0,3.0,246.0
28,1762558541,19.0,0.0,17.0,33.0
29,1805642291,11.0,8.0,9.0,16.0
...,...,...,...,...,...
25464,3169321620,9.0,8.0,8.0,251.0
25465,4246557753,2.0,0.0,0.0,0.0
25466,1345381188,9.0,0.0,3.0,11.0
25467,388038662,7.0,0.0,7.0,85.0
25468,2913463627,100.0,2.0,62.0,107.0
25469,571947719,7.0,14.0,6.0,1284.0
25470,486178085,6.0,1.0,2.0,72.0
25471,3397562981,145.0,3.0,32.0,86.0
25472,787562214,8.0,3.0,8.0,70.0
25473,3230650403,16.0,0.0,7.0,18.0
25474,1187117667,1.0,0.0,0.0,0.0
25475,2309311781,6.0,4.0,0.0,23.0
25476,31247346,53.0,32.0,40.0,1907.0
25477,1503247688,10.0,0.0,13.0,27.0
25478,726631277,64.0,0.0,23.0,3049.0
25479,0,0.0,0.0,0.0,0.0
25480,903610;725003486;2824841189;998821667;55525628...,201.0,0.0,0.0,0.0
25481,439904567,48.0,224.0,19.0,914.0
25482,1061085362,9.0,2.0,1.0,167.0
25483,3100757952,9.0,0.0,8.0,10.0
25484,793834522,5.0,30.0,8.0,369.0
25485,3127485387,22.0,1.0,20.0,25.0
25486,2415054310,86.0,26.0,72.0,813.0
25487,1796148403,5.0,0.0,6.0,21.0
25488,3075319534,15.0,16.0,13.0,524.0
25489,110980591,0.0,0.0,3.0,34.0
25490,582973300,8.0,1.0,1.0,20.0
25491,1294481466,12.0,1.0,12.0,49.0
25492,2252745757,10.0,0.0,8.0,7.0
25493,1187086028,6.0,0.0,6.0,4.0

In [9]:
event_attendees1=event_attendees1.rename(columns={'event': 'event_id'})

In [11]:
events2=events.merge(event_attendees1, on='event_id', how='left')

In [14]:
events2.describe()

,user_id,lat,lng,c_1,c_2,c_3,c_4,c_5,c_6,c_7,...,c_96,c_97,c_98,c_99,c_100,c_other,yes_count,no_count,maybe_count,invited_count
count,3.137972e+06,1.806092e+06,1.806092e+06,3.137972e+06,3.137972e+06,3.137972e+06,3.137972e+06,3.137972e+06,3.137972e+06,3.137972e+06,...,3.137972e+06,3.137972e+06,3.137972e+06,3.137972e+06,3.137972e+06,3.137972e+06,0.0,0.0,0.0,0.0
mean,2.114831e+09,3.393515e+01,-5.748120e+01,2.324834e+00,1.692952e+00,1.451996e+00,1.071046e+00,1.051598e+00,9.937807e-01,8.436293e-01,...,7.978465e-02,7.888503e-02,7.959695e-02,7.917598e-02,7.789649e-02,4.173811e+01,NaN,NaN,NaN,NaN
std,1.264534e+09,1.897208e+01,6.540928e+01,4.095202e+00,2.845647e+00,2.612183e+00,1.904300e+00,2.283144e+00,3.456083e+00,1.896622e+00,...,3.926603e-01,1.068604e+00,3.399542e-01,4.278229e-01,3.453929e-01,4.939340e+01,NaN,NaN,NaN,NaN
min,5.660000e+02,-8.615100e+01,-1.764570e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN
25%,9.866086e+08,3.286500e+01,-9.714500e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.200000e+01,NaN,NaN,NaN,NaN
50%,2.104379e+09,3.964100e+01,-7.946400e+01,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.800000e+01,NaN,NaN,NaN,NaN
75%,3.216721e+09,4.335900e+01,-4.764750e+00,3.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.500000e+01,NaN,NaN,NaN,NaN
max,4.294966e+09,7.821800e+01,1.793170e+02,2.186000e+03,3.010000e+02,2.530000e+02,2.080000e+02,1.801000e+03,5.050000e+02,2.120000e+03,...,4.500000e+01,1.801000e+03,1.900000e+01,3.600000e+01,4.100000e+01,9.664000e+03,NaN,NaN,NaN,NaN

In [ ]:
users=pd.read_csv('/Users/boris/Desktop/OZP/users.csv',delimiter=',')

In [ ]:
users.head

In [ ]:
event_attendees=pd.read_csv('/Users/boris/Desktop/OZP/event_attendees.csv',delimiter=',')

In [ ]:
train1=train.merge(users, on='user_id', how='inner')

In [ ]:
train1

In [ ]:
train1=train1.merge(events, on='event_id', how='inner')

In [ ]:
event_attendees

In [ ]:
event_attendees['yes_count']=event_attendees.yes.str.count(';')+1
event_attendees['no_count']=event_attendees.no.str.count(';')+1
event_attendees['maybe_count']=event_attendees.maybe.str.count(';')+1
event_attendees['invited_count']=event_attendees.invited.str.count(';')+1

In [ ]:
event_attendees1=event_attendees.drop(axis=1,labels={'yes','maybe','no','invited'})

In [ ]:
event_attendees1

In [ ]:
event_attendees1.fillna(0, inplace=True)

In [ ]:
event_attendees1

In [ ]:
train1=train1.rename(columns={'user_id_x': 'user_id', 'user_id_y': 'user_event_creator'})

In [ ]:
train1

In [ ]:
event_attendees1=event_attendees1.rename(columns={'event': 'event_id'})

In [ ]:
event_attendees1

In [ ]:
train2=train1.merge(event_attendees1, on='event_id', how='inner')

##

train2

In [ ]:
train2

In [ ]:
 train1.location

In [ ]:
unique_user_locations=pd.DataFrame(train1.location.unique(), columns=['location'])

In [ ]:
unique_user_locations

In [ ]:
!pip install mapbox

In [ ]:
import mapbox

In [ ]:
geocoder = mapbox.Geocoder(access_token='pk.eyJ1IjoibWlsb3NtODMiLCJhIjoiY2pkcGM1aXJhMWs4MzMzcWhpMHpobW9paCJ9.smkRAuDMn-2txP_ybEiqqA')

In [ ]:
response = geocoder.forward('Beograd')

In [ ]:
response.geojson()

In [ ]:
user_lat=response.geojson()['features'][1]['geometry']['coordinates'][1]
user_lng=response.geojson()['features'][1]['geometry']['coordinates'][0]

In [ ]:
print(str(user_lat)+','+str(user_lng))

In [ ]:
unique_user_locations['location'].str.strip()
unique_user_locations['location'].replace('', np.nan, inplace=True)
unique_user_locations.dropna(inplace=True)

In [ ]:
unique_user_locations

In [ ]:
unique_user_locations['user_lat']=''
unique_user_locations['user_lng']=''

In [ ]:
for i, row in unique_user_locations.iterrows():
    response=geocoder.forward(row.location)
    if len(response.geojson()['features'])>0:
        unique_user_locations.set_value(i,'user_lat',response.geojson()['features'][0]['geometry']['coordinates'][1])
        unique_user_locations.set_value(i,'user_lng',response.geojson()['features'][0]['geometry']['coordinates'][0])

In [ ]:
unique_user_locations

In [ ]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(unique_user_locations)

In [ ]:
train1=train1.merge(unique_user_locations, on='location', how='left')

In [ ]:
with pd.option_context('display.max_rows', 100, 'display.max_columns', None):
    print(train1.loc[:,'city':'country'][(pd.isnull(train1.lat)) & (pd.isnull(train1.city)==False)])